-- Phase 8: technical monitoring history (sessions + technical events).
-- Additive only: creates new tables, never alters or drops existing ones.
-- Times are stored in UTC.

CREATE TABLE IF NOT EXISTS monitoring_sessions (
    id                      CHAR(36)     NOT NULL,              -- UUID generated by the app (retry-safe inserts)
    started_by              INT          NULL,                  -- users.id of whoever pressed Start (no FK: history outlives users)
    started_at              DATETIME(3)  NOT NULL,
    ended_at                DATETIME(3)  NULL,                  -- NULL while running or if interrupted
    status                  VARCHAR(20)  NOT NULL,              -- RUNNING | COMPLETED | INTERRUPTED
    frames_processed        INT          NOT NULL DEFAULT 0,
    average_processing_fps  FLOAT        NULL,
    average_latency_ms      FLOAT        NULL,                  -- mean of once-per-second samples
    model_provider          VARCHAR(40)  NOT NULL,              -- 'none' when no model is enabled
    model_name              VARCHAR(80)  NULL,
    model_version           VARCHAR(40)  NULL,
    model_is_mock           TINYINT(1)   NOT NULL DEFAULT 0,
    model_development_only  TINYINT(1)   NOT NULL DEFAULT 0,
    feature_schema_version  INT          NOT NULL,
    created_at              DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_monitoring_sessions_started_at (started_at),
    KEY idx_monitoring_sessions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS monitoring_events (
    id                      BIGINT       NOT NULL AUTO_INCREMENT,
    session_id              CHAR(36)     NOT NULL,
    timestamp               DATETIME(3)  NOT NULL,              -- when the condition was observed
    frame_id                INT          NULL,
    event_type              VARCHAR(40)  NOT NULL,              -- SESSION_STARTED, CAMERA_UNAVAILABLE, MODEL_ERROR, ...
    status                  VARCHAR(40)  NULL,                  -- backend state value at that moment
    model_provider          VARCHAR(40)  NULL,
    model_name              VARCHAR(80)  NULL,
    model_version           VARCHAR(40)  NULL,
    feature_schema_version  INT          NOT NULL,
    is_mock                 TINYINT(1)   NOT NULL DEFAULT 0,
    development_only        TINYINT(1)   NOT NULL DEFAULT 0,
    error_message           VARCHAR(500) NULL,
    created_at              DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_monitoring_events_session_time (session_id, timestamp),
    CONSTRAINT fk_monitoring_events_session FOREIGN KEY (session_id)
        REFERENCES monitoring_sessions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
